### ISSUE TITLE
Doesn't show any visual indicators, doesn't fix problems reported by command line

### ISSUE THREAD

**Issue by elliottregan** [apexskier/nova-eslint-forked#20] opened 2020-09-23 15:28 UTC
I don't get any visual indicators in my .JS files about errors, but they do show up in the terminal running my Webpack dev server.

**To reproduce**

1. Set up ESLint. I have a .eslintrc.js file in my root.
2. Make a JS error or break an ESLint rule
3. Nothing happens
4. I click "fix all issues" from the content menu, I see the log "Fixing [file path]/index.js", but...
5. Nothing happens

**Expected behavior**

I'd expect to see some visual clue that I made a mistake, or for it to be automatically fixed on save.

**Screenshots**

I can provide some if needed. 

**Environment**

- Nova version: 1.1
- Extension version:  1.1.0
- ESLint version: 7.8.1
- macOS version: 10.15.6
- NodeJS information:
  - node version: 14.6.0
  - npm version: 6.14.7
  - installation method: nvm

**Extension console output**

```
ESLint[8:59:49.852000] activating...

ESLint[8:59:49.852000] activated

ESLint[8:59:50.044000] npm bin: env: npm: No such file or directory

```
**Additional context**

I'm just trying out Nova, on the trial. I haven't had any luck getting other filetypes to get highlighted, so it could be something unrelated to this plugin.

`eslint` are both available globally, but my understanding is this plugin should use the version installed in the project root. I also tried adding the output of `which eslint` as the "Path to ESLint executable", but that doesn't change anything (I get the same "npm: no such file..." in the console.

**Comment by tommasongr** [comment] 2020-09-23 15:46
What type of file are u working on @elliottregan? Right now ESLint supports only js, ts and jsx. There is an open issue for supporting other file types #9

**Comment by elliottregan** [comment] 2020-09-23 15:47
Just .JS. Haven't tried TypeScript out yet.

**Comment by elliottregan** [comment] 2020-09-23 16:50
If it helps, I haven't done anything differently from my VS Code, Sublime, etc. setup. ESLint in those editors works as expected.

**Comment by apexskier** [comment] 2020-09-25 18:45
@elliottregan What shell are you using (e.g. bash, zsh)? If it's bash, this is possibly caused by the same root cause as https://github.com/apexskier/nova-typescript/issues/64#issuecomment-696921316.

**Comment by elliottregan** [comment] 2020-09-25 19:13
I'm using bash 5.0, installed through homebrew.

Switching to the Mac OS's zsh does seem to fix the `TypeScript Error: Failed to install:` alert I get when opening Nova, buuut... it causes Nova to crash when opening any .js file. Switching back to bash "fixes" things (same state as my original bug report). 

Here's the entire output of my Nova Preferences > Tools environment:
```
BASH_COMPLETION_COMPAT_DIR=/usr/local/etc/bash_completion.d
HOME=/Users/btp
NVM_CD_FLAGS=
NVM_DIR=/.nvm
NVM_RC_VERSION=
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/
SHELL=/usr/local/bin/bash
SHLVL=0
TMPDIR=/var/folders/zb/gthn_9c53qv615yhq80vml880000gn/T/
USER=btp
```

Happy to provide more info if there's something specific you'd like to see.

**Comment by apexskier** [comment] 2020-09-25 19:16
`NVM_DIR=/.nvm` confirms my suspicion that you're getting hit by that same bug. The crashing issue is going to be nova core, not much I can do - it sounds like https://github.com/apexskier/nova-typescript/issues/74.

We'll have to wait until Nova 1.2, the Nova devs indicated they've got that Bash issue on deck.

**Comment by elliottregan** [comment] 2020-10-01 20:12
I updated to 1.2 today, and now I have this error:

```
Extension encountered an uncaught exception:
/Users/btp/Library/Application Support/Nova/Extensions/apexskier.eslint/Scripts/main.dist.js (Line 265, Column 0)
Error: Error launching process: /Users/btp/.nvm/versions/node/v14.6.0/bin/, The operation couldn’t be completed. Permission denied
    [native code]
    getLintMessages@file:///Users/btp/Library/Application%20Support/Nova/Extensions/apexskier.eslint/Scripts/main.dist.js:265:26
    runEslint@file:///Users/btp/Library/Application%20Support/Nova/Extensions/apexskier.eslint/Scripts/main.dist.js:289:24
    file:///Users/btp/Library/Application%20Support/Nova/Extensions/apexskier.eslint/Scripts/main.dist.js:346:50
    file:///Users/btp/Library/Application%20Support/Nova/Extensions/apexskier.eslint/Scripts/main.dist.js:339:24
    watchEditor@file:///Users/btp/Library/Application%20Support/Nova/Extensions/apexskier.eslint/Scripts/main.dist.js:525:28
```

We're getting somewhere... Again, let me know if you'd like some help digging in.

**Comment by apexskier** [comment] 2020-10-04 15:59
@elliottregan Nova 1.2 has a fix for the original issue of messed up PATH variables in nvm.

For your new new issue...

`Error: Error launching process: /Users/btp/.nvm/versions/node/v14.6.0/bin/, The operation couldn’t be completed. Permission denied`

That path there appears to be a directory, but it should be the eslint executable (output of `$(npm bin)/eslint`). The latest version of the extension explicitly checks if that path is executable, so you actually shouldn't see anything at all - can you make sure you're on the latest update (1.2.1)?

I checked the stack trace, and that's coming from https://github.com/apexskier/nova-eslint/blob/7c2f1c94ffa1fc29eb20c41df0b15b70a4180ce4/src/process.ts#L119. The identifier producing that path is `eslint`, which comes from https://github.com/apexskier/nova-eslint/blob/7c2f1c94ffa1fc29eb20c41df0b15b70a4180ce4/src/getEslintPath.ts#L28

I'm not exactly sure how nvm structures the filesystem, but the core issue you're now having is somewhere in that function I think.

Can you let me know the following:

1. Do you have a custom eslint path set in the workspace or global preferences, and if so what is it?
   <img width="240" alt="Screen Shot 2020-10-04 at 17 53 19" src="https://user-images.githubusercontent.com/329222/95020309-a6393880-066a-11eb-8d0f-69e77b5bf1cb.png">
   <img width="240" alt="Screen Shot 2020-10-04 at 17 53 29" src="https://user-images.githubusercontent.com/329222/95020312-a9ccbf80-066a-11eb-8b12-59247b501505.png">
2. What's the output of `npm bin` from a terminal opened within your Nova workspace?

**Comment by apexskier** [comment] 2020-10-29 08:11
Closing due to age. Please open a new issue if you're still having problems

**Closed as completed by apexskier** 2020-10-29 08:11 UTC
Labels: bug, nova-core
